/*
Provide 2 examples of possible data structures to describe the game state
Think about an empty board, partially completed, and fully completed.
*/


// These examples use a data structure, with different states
// that are generated by an outside function

const Game1 = {
    board: [null, null, null, null, null],
    state: 'empty'
}

const Game2 = {
    board: ['W', 'E', 'A', 'R', 'Y'],
    state: 'partially completed'
}

const Game3 = {
    board: ['W', 'O', 'R', 'D', 'L'],
    state: 'fully completed'
}



// These examples use a data structure
// where each letter has it's own state

const State = {
    Empty: 'E',
    Incorrect: 'I',
    IncorrectPosition: 'P',
    Correct: 'C'
}
const Board1 = {
    position: [
        {letter: null, state: State.Empty},
        {letter: null, state: State.Empty},
        {letter: null, state: State.Empty},
        {letter: null, state: State.Empty},
        {letter: null, state: State.Empty}
    ],
    state: 'empty'
}
const Board2 = {
    position: [
        {letter: 'W', state: State.Correct},
        {letter: 'E', state: State.Incorrect},
        {letter: 'A', state: State.Incorrect},
        {letter: 'R', state: State.IncorrectPosition},
        {letter: 'Y', state: State.Incorrect}
    ],
    state: 'partially complete'
}
const Board3 = {
    position: [
        {letter: 'W', state: State.Correct},
        {letter: 'O', state: State.Correct},
        {letter: 'R', state: State.Correct},
        {letter: 'D', state: State.Correct},
        {letter: 'L', state: State.Correct}
    ],
    state: 'fully complete'
}
